MvcKütüphane/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKütüphane.Controllers;
using MvcKütüphane.Models.Entity;

namespace MvcKütüphane.Controllers
{
    public class KitapController : Controller
    {
        // GET: Kitap
        DBKÜTÜPHANEEntities db = new DBKÜTÜPHANEEntities();
        public ActionResult Index(string p)
        {
            var kitaplar = from k in db.TBLKİTAP select k;
            if (!string.IsNullOrEmpty(p))
            {
                kitaplar = kitaplar.Where(x => x.AD.Contains(p));
            }
            //var kitaplar = db.TBLKİTAP.ToList();
            return View(kitaplar.ToList());
        }
        [HttpGet]
        public ActionResult KitapEkle()
        {
            List<SelectListItem> deger1 = (from i in db.TBLKATEGORİ.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            List<SelectListItem> deger2 = (from i in db.TBLYAZAR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD + ' ' + i.SOYAD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            return View();
        }
        [HttpPost]
        public ActionResult KitapEkle(TBLKİTAP p)
        {
            var ktg = db.TBLKATEGORİ.Where(k => k.ID == p.TBLKATEGORİ.ID).FirstOrDefault();
            var yzr = db.TBLYAZAR.Where(y => y.ID == p.TBLYAZAR.ID).FirstOrDefault();
            p.TBLKATEGORİ =ktg;
            p.TBLYAZAR = yzr;
            db.TBLKİTAP.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapSil(int id)
        {
            var kitap = db.TBLKİTAP.Find(id);
            db.TBLKİTAP.Remove(kitap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapGetir(int id)
        {
            var ktp = db.TBLKİTAP.Find(id);
            List<SelectListItem> deger1 = (from i in db.TBLKATEGORİ.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from i in db.TBLYAZAR.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD + ' ' + i.SOYAD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            ViewBag.dgr1 = deger1;
            return View("KitapGetir", ktp);
        }
        public ActionResult KitapGüncelle(TBLKİTAP p)
        {
            var kitap = db.TBLKİTAP.Find(p.ID);
            kitap.AD = p.AD;
            kitap.BASIMYIL = p.BASIMYIL;
            kitap.SAYFA = p.SAYFA;
            kitap.YAYINEVİ = p.YAYINEVİ;
            kitap.DURUM = true;
            var ktg = db.TBLKATEGORİ.Where(k =>k.ID == p.TBLKATEGORİ.ID).FirstOrDefault();
            var yzr = db.TBLYAZAR.Where(y => y.ID == p.TBLYAZAR.ID).FirstOrDefault();
            kitap.KATEGORİ = ktg.ID;
            kitap.YAZAR = yzr.ID;
            kitap.KITAPRESIM = p.KITAPRESIM;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKütüphane/Views/Kitap/Index.cshtml
@using MvcKütüphane.Models.Entity
@model List<TBLKİTAP>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Kitap Sayfası</h2>

@using (Html.BeginForm("Index", "Kitap", FormMethod.Get))
{
    <div style="margin-bottom:15px; margin-top:15px;"></div>
    <b>Kitap Ara:</b> @Html.TextBox("p")
<input type="submit" value="Ara" />
}


<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Ad</th>
        <th>Kitap Yazarı</th>
        <th>Kategori</th>
        <th>Basım Yılı</th>
        <th>Yayınevi</th>
        <th>Sayfa</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ID</td>
            <td>@item.AD</td>
            <td>@item.TBLYAZAR.AD&nbsp @item.TBLYAZAR.SOYAD</td>
            <td>@item.TBLKATEGORİ.AD</td>
            <td>@item.BASIMYIL</td>
            <td>@item.YAYINEVİ</td>
            <td>@item.SAYFA</td>
            <td>@item.DURUM</td>
            <td><a href="/Kitap/KitapSil/@item.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Kitap/KitapGetir/@item.ID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }

</table>
<a href="/Kitap/KitapEkle/" class="btn btn-primary">Yeni Kitap Ekle</a>

MvcKütüphane/Views/Kitap/KitapEkle.cshtml
@model MvcKütüphane.Models.Entity.TBLKİTAP
@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>KitapEkle</h2>

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Kitap Adı</label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Kategori</label>
        @Html.DropDownListFor(k => k.TBLKATEGORİ.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Yazar</label>
        @Html.DropDownListFor(k => k.TBLYAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Basım yılı</label>
        @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yayınevi</label>
        @Html.TextBoxFor(k => k.YAYINEVİ, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Sayfa Sayısı</label>
        @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Resim Linki</label>
        @Html.TextBoxFor(k => k.KITAPRESIM, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Kitap Ekle</button>
    </div>
    <input type="hidden" name="DURUM" value="true" />
</form>

MvcKütüphane/Views/Kitap/KitapGetir.cshtml
@model MvcKütüphane.Models.Entity.TBLKİTAP
@{
    ViewBag.Title = "KitapGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>KitapGetir</h2>

@using (Html.BeginForm("KitapGüncelle", "Kitap", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <div style="margin-bottom:15px">
            <label>Kitap Id</label>
            @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>kitap Adı</label>
            @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Kategori</label>
            @Html.DropDownListFor(k => k.TBLKATEGORİ.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Yazarı</label>
            @Html.DropDownListFor(k => k.TBLYAZAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Basım Yılı</label>
            @Html.TextAreaFor(k => k.BASIMYIL, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Yayonevi</label>
            @Html.TextAreaFor(k => k.YAYINEVİ, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Sayfa</label>
            @Html.TextAreaFor(k => k.SAYFA, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Kitap Resim Linki</label>
            @Html.TextBoxFor(k => k.KITAPRESIM, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <button class="btn btn-warning"> Kitap Bilgilerini Güncelle</button>
        </div>
    </div>
}