MvcKütüphane/Controllers/OduncController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKütüphane.Models.Entity;

namespace MvcKütüphane.Controllers
{
    public class OduncController : Controller
    {
        // GET: Odunc
        DBKÜTÜPHANEEntities db = new DBKÜTÜPHANEEntities();
        [Authorize(Roles ="A")]
        public ActionResult Index()
        {
            var degerler = db.TBLHAREKET.Where(x =>x.ISLEMDURUM == false).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult OduncVer()
        {
            List<SelectListItem>deger1 = (from x in db.TBLÜYELER.ToList()
                                          select new SelectListItem
                                          {
                                              Text=x.AD +" "+ x.SOYAD,
                                              Value = x.ID.ToString()
                                          }).ToList();

            List<SelectListItem> deger2 = (from x in db.TBLKİTAP.Where(x=>x.DURUM==true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.AD,
                                               Value = x.ID.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from x in db.TBLPERSONEL.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PERSONEL,
                                               Value = x.ID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult OduncVer(TBLHAREKET o)
        {
            var d1 = db.TBLÜYELER.Where(x => x.ID == o.TBLÜYELER.ID).FirstOrDefault();
            var d2 = db.TBLKİTAP.Where(x => x.ID == o.TBLKİTAP.ID).FirstOrDefault();
            var d3 = db.TBLPERSONEL.Where(x => x.ID == o.TBLPERSONEL.ID).FirstOrDefault();
            o.TBLÜYELER = d1;
            o.TBLKİTAP = d2;
            o.TBLPERSONEL = d3;
            db.TBLHAREKET.Add(o);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Odunciade(TBLHAREKET p)
        {
            var odn =db.TBLHAREKET.Find(p.ID);
            DateTime d1 = DateTime.Parse(odn.IADETARIH.ToString());
            DateTime d2 = Convert.ToDateTime(DateTime.Now.ToString());
            TimeSpan d3 = d2 - d1;
            ViewBag.dgr = d3.TotalDays;
            return View("Odunciade",odn);
        }
        public ActionResult OduncGuncelle(TBLHAREKET p)
        {
            var hrk = db.TBLHAREKET.Find(p.ID);
            hrk.UYEGETIRTARIH = p.UYEGETIRTARIH;
            hrk.ISLEMDURUM = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKütüphane/Views/Odunc/Index.cshtml
@using MvcKütüphane.Models.Entity
@model List<TBLHAREKET>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Ödünç Kitap Listesi</h2>

<table class="table table-bordered">
    <tr>
        <th>İşlem Id</th>
        <th>Kitap Adı</th>
        <th>Üye Id</th>
        <th>Personel</th>
        <th>Alış Tarihi</th>
        <th>İade Tarihi</th>
        <th>İade Al</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ID</td>
            <td>@item.TBLKİTAP.AD</td>
            <td>@item.TBLÜYELER.AD&nbsp @item.TBLÜYELER.SOYAD</td>
            <td>@item.TBLPERSONEL.PERSONEL</td>
            <td>@Convert.ToDateTime(item.ALISTARIH).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(item.IADETARIH).ToString("dd/MM/yyyy")</td>
            <td><a href="/Odunc/Odunciade/@item.ID" class="btn btn-default" style="background-color:#ff6a00;color:white">Kitabı İade Et</a></td>
        </tr>
    }

</table>

MvcKütüphane/Views/Odunc/OduncVer.cshtml
@model MvcKütüphane.Models.Entity.TBLHAREKET
@{
    ViewBag.Title = "OduncVer";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Ödünç Ver</h2>

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Üye ID</label>
        @*@Html.TextBoxFor(k => k.UYE, new { @class = "form-control" })*@
        @Html.DropDownListFor(k=>k.TBLÜYELER.ID,(List<SelectListItem>)ViewBag.dgr1,new {@class = "form-control"})
        
    </div>
    <div style="margin-top:15px">
        <label>Kitap ID</label>
        @*@Html.TextBoxFor(k => k.UYE, new { @class = "form-control" })*@
        @Html.DropDownListFor(k => k.TBLKİTAP.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Personel ID</label>
        @*@Html.TextBoxFor(k => k.PERSONEL, new { @class = "form-control" })*@
        @Html.DropDownListFor(k => k.TBLPERSONEL.ID, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Alış Tarihi</label>
        <input type="text" class="form-control" name="ALISTARIH" value="@DateTime.Now.ToShortDateString()"/>
    </div>
    <div style="margin-top:15px">
        <label>Kitap Veriş Tarihi</label>
        <input type="text" class="form-control" name="IADETARIH" value="@DateTime.Now.AddDays(7).ToShortDateString()" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-group" style="background-color:#b47777; color:white">Kitabı Ödünç Ver</button>
        <input type="hidden" name="ISLEMDURUM" value="False" />
    </div>
</form>

MvcKütüphane/Views/Odunc/Odunciade.cshtml
@model MvcKütüphane.Models.Entity.TBLHAREKET
@{
    ViewBag.Title = "Odunciade";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Ödünç İade</h2>

@using (Html.BeginForm("OduncGuncelle", "Odunc", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <label>Haraket ID</label>
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        <label>Kiap Adı</label>
        @Html.TextBoxFor(k => k.TBLKİTAP.AD, new { @class = "form-control" })
        <br />
        <label>Üye</label>
        @Html.TextBoxFor(k => k.TBLÜYELER.AD, new { @class = "form-control" })
        <br />
        <label>Personel</label>
        @Html.TextBoxFor(k => k.TBLPERSONEL.PERSONEL, new { @class = "form-control" })
        <label>Alış Tarihi</label>
        @Html.TextBoxFor(k => k.ALISTARIH,"{0: dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>Normal İade Tarihi</label>
        @Html.TextBoxFor(k => k.IADETARIH, new { @class = "form-control" })
        <br />
        <label>Üyenin Getirdiği Tarih</label>
        <input type="text" class="form-control" name="UYEGETORTARIH" value="@DateTime.Now.ToShortDateString()" />
        <br />
        <label>Geç Gelen Gün Sayıs</label>
        <input type="text" class="form-control" id="Gecinput" value="@ViewBag.dgr" />
    </div>
    <br />
    <div>
        <button class="btn btn-warning">Ödünç Kitabı Geri Al</button>
    </div>
}