MvcKütüphane/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKütüphane.Models.Entity;
namespace MvcKütüphane.Controllers
{
    public class YazarController : Controller
    {
        // GET: Yazar
        DBKÜTÜPHANEEntities db = new DBKÜTÜPHANEEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLYAZAR.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YazarEkle()
        {
            return View();
        }
        public ActionResult YazarEkle(TBLYAZAR p)
        {
            if (!ModelState.IsValid)
            {
                return View("YazarEkle");
            }
            db.TBLYAZAR.Add(p);
            db.SaveChanges();
            return View();
        }
        public ActionResult YazarSil(int id) 
        {
            var yazar = db.TBLYAZAR.Find(id);
            db.TBLYAZAR.Remove(yazar);
            db.SaveChanges();
            return RedirectToAction("Index"); 
        }
        public ActionResult YazarGetir(int id)
        {
            var yzr = db.TBLYAZAR.Find(id);
            return View("YazarGetir",yzr);
        }
        public ActionResult YazarGüncelle(TBLYAZAR p)
        {
            var yzr = db.TBLYAZAR.Find(p.ID);
            yzr.AD =p.AD;
            yzr.SOYAD =p.SOYAD;
            yzr.DETAY =p.DETAY;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult YazarKitaplar (int id)
        {
            var yazar = db.TBLKİTAP.Where(x =>x.YAZAR == id).ToList();
            var yzrad = db.TBLYAZAR.Where(y=>y.ID == id).Select(z=>z.AD +" "+ z.SOYAD).FirstOrDefault();
            ViewBag.y1 = yzrad;
            return View(yazar);
        }
    }
}

MvcKütüphane/Views/Yazar/Index.cshtml
@using MvcKütüphane.Models.Entity
@model List<TBLYAZAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Yazarlar</h2>

<table class="table table-striped">
    <tr style="background-color:rgb(252, 178, 22)">
        <th>Id</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Yazarın Kitapları</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ID</td>
            <td>@item.AD</td>
            <td>@item.SOYAD</td>
            <td>@Html.ActionLink("Sil", "YazarSil", new { id = item.ID }, new { @class = "btn btn-danger", onclick = "return confirm('Silmek İstiyor Musunuz ?')" })</td>
            <td><a href="/Yazar/YazarGetir/@item.ID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/Yazar/YazarKitaplar/@item.ID" class="btn btn-default"
                   style="background-color:lightcoral; color:wheat">Yazarın Kitapları</a></td>
        </tr>
    }
</table>
<a class="btn btn-primary" href="/Yazar/YazarEkle/">Yeni Yazar Ekle</a>

MvcKütüphane/Views/Yazar/YazarEkle.cshtml
@model MvcKütüphane.Models.Entity.TBLYAZAR
@{
    ViewBag.Title = "YazarEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Yazar Adı</label>
        @Html.TextBoxFor(y => y.AD, new { @class = "form-control" })
        @Html.ValidationMessageFor(y => y.AD)
        @Html.ValidationMessageFor(y => y.SOYAD)
    </div>
    <div style="margin-top:15px">
        <label>Yazar Soyadı</label>
        @Html.TextBoxFor(y => y.SOYAD, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yazar Detayı</label>
        @Html.TextBoxFor(y => y.DETAY, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Yazar Ekle</button>
    </div>
</form>

MvcKütüphane/Views/Yazar/YazarGetir.cshtml
@model MvcKütüphane.Models.Entity.TBLYAZAR
@{
    ViewBag.Title = "YazarGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("YazarGüncelle", "Yazar", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>
    <div class="form-group">
        <div style="margin-bottom:15px">
            <label>Yazar Id</label>
            @Html.TextBoxFor(y => y.ID, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Yazar Adı</label>
            @Html.TextBoxFor(y => y.AD, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Yazar Soyadı</label>
            @Html.TextBoxFor(y => y.SOYAD, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <label>Yazar Detay</label>
            @Html.TextAreaFor(y => y.DETAY, new { @class = "form-control" })
        </div>
        <div style="margin-bottom:15px">
            <button class="btn btn-warning"> Yazar Bilgilerini Güncelle</button>
        </div>
    </div>
}

MvcKütüphane/Views/Yazar/YazarKitaplar.cshtml
@using MvcKütüphane.Models.Entity
@model List<TBLKİTAP>
@{
    ViewBag.Title = "YazarKitaplar";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Yazar: @ViewBag.y1</h2>
<br />
<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Kategori</th>
        <th>Yayınevi</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ID</td>
            <td>@item.AD</td>
            <td>@item.TBLKATEGORİ.AD</td>
            <td>@item.YAYINEVİ</td>
        </tr>
    }
</table>